# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title SVD using RcppArmadillo
#' @description A faster SVD than R
#' @param X a numeric matrix
#' @return SVD Decomposition Right Matrix
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22088
#' @examples
#' \dontrun{
#' X<-matrix(1:10,ncol=2)
#' res <- SVD_V(X)
#' }
#' @export
SVD_V <- function(X) {
    .Call('_StatComp22088_SVD_V', PACKAGE = 'StatComp22088', X)
}

#' @title Scaling and Centering of Matrix-like Objects
#' @description center and scale the columns of a numeric matrix.
#' @param X a numeric matrix
#' @param center centralization or not
#' @param scale standardization or not
#' @return centered and scaled matrix
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22088
#' @examples
#' \dontrun{
#' X<-matrix(1:10,ncol=2)
#' res <- scaleC(X,center=T,scale=T)
#' }
#' @export
scaleC <- function(X, center, scale) {
    .Call('_StatComp22088_scaleC', PACKAGE = 'StatComp22088', X, center, scale)
}

#' @title SVD using RcppArmadillo also
#' @description First k singular values and vectors for sparse matrix
#' @param X a sparse matrix
#' @param k number of expected singular values
#' @return First k vectors of SVD Decomposition Right Matrix
#' @import Rcpp
#' @import RcppArmadillo
#' @useDynLib StatComp22088
#' @examples
#' \dontrun{
#' X<-matrix(sample(0:2,size=20,replace=T,prob = c(0.8,0.1,0.1)),ncol=4)
#' res <- SVDS_V(X)
#' }
#' @export
SVDS_V <- function(X, k = 10L) {
    .Call('_StatComp22088_SVDS_V', PACKAGE = 'StatComp22088', X, k)
}

#' @title Gibbs sampler in homework
#' @description Gibbs sampler in homework for two dimensional normal state
#' @param mu1 mean
#' @param mu2 mean
#' @param sigma1 standard deviation
#' @param sigma2 standard deviation
#' @param rho coefficient of correlation
#' @param N numbers
#' @return a random sample of size \code{N}
#' @import Rcpp
#' @useDynLib StatComp22088
#' @examples
#' \dontrun{
#' mu1=mu2=0
#' sigma1=sigma2=1
#' rho=0.9
#' N=100
#' gib<-gibbsC(mu1,sigma1,mu2,sigma2,rho,N)
#' }
#' @export
gibbsC <- function(mu1, sigma1, mu2, sigma2, rho, N) {
    .Call('_StatComp22088_gibbsC', PACKAGE = 'StatComp22088', mu1, sigma1, mu2, sigma2, rho, N)
}

